/**********************************************************************************************************************
 * \file GTM_TOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM    20                                      /* Interrupt priority number                    */
#define FAN                 IfxGtm_TOM0_9_TOUT1_P02_1_OUT
#define SERVO               IfxGtm_TOM0_13_TOUT5_P02_5_OUT
#define PWM_PERIOD          100000                                   /* PWM period for the TOM                       */
#define SERVO_PWM           2000000

#define SERVO_PWM_CENTER    150000
#define SERVO_PWM_MIN       100000
#define SERVO_PWM_MAX       200000
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
// FAN용
IfxGtm_Tom_Pwm_Config g_fanConfig;
IfxGtm_Tom_Pwm_Driver g_fanDriver;

// SERVO용
IfxGtm_Tom_Pwm_Config g_servoConfig;
IfxGtm_Tom_Pwm_Driver g_servoDriver;
uint32 g_fadeValue = 0;                                             /* Fade value, starting from 0                  */
sint8 g_fadeDir = 1;                                                /* Fade direction variable                      */




/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void setDutyCycle(uint32 dutyCycle);                                /* Function to set the duty cycle of the PWM    */
//void controlFan(void);
/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the TOM */
void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_fanConfig, &MODULE_GTM);

    g_fanConfig.tom = FAN.tom;                                      /* Select the TOM depending on the LED          */
    g_fanConfig.tomChannel = FAN.channel;                           /* Select the channel depending on the LED      */
    g_fanConfig.period = PWM_PERIOD;                                /* Set the timer period                         */
    g_fanConfig.dutyCycle = 0;
    g_fanConfig.pin.outputPin = &FAN;                               /* Set the LED port pin as output               */
    g_fanConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&g_fanDriver, &g_fanConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_fanDriver, TRUE);                       /* Start the PWM                                */
}
void initServoPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock*/
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_servoConfig, &MODULE_GTM);

    g_servoConfig.tom = SERVO.tom;                                      /* Select the TOM depending on the LED          */
    g_servoConfig.tomChannel = SERVO.channel;                           /* Select the channel depending on the LED      */
    g_servoConfig.period = SERVO_PWM;                                /* Set the timer period                         */
    g_servoConfig.dutyCycle = SERVO_PWM_CENTER;
    g_servoConfig.pin.outputPin = &SERVO;                               /* Set the LED port pin as output               */
    g_servoConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&g_servoDriver, &g_servoConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_servoDriver, TRUE);                       /* Start the PWM                                */
}


/* This function sets the duty cycle of the PWM */
void setDutyCycle(uint32 dutyCycle)
{
    g_fanConfig.dutyCycle = dutyCycle;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_fanDriver, &g_fanConfig);                /* Re-initialize the PWM                        */

}

void setSERVODutyCycle(uint32 dutyCycle)
{
    g_servoConfig.dutyCycle = dutyCycle;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_servoDriver, &g_servoConfig);                /* Re-initialize the PWM                        */

}


