/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

// my include
#include <asclin_driver/asclin.h>
#include <stm_driver/stm.h>
#include <mq135_driver/mq135.h>
#include <dht22_driver/dht22.h>
#include <mhz19b_driver/mhz19b.h>
#include <hvac_ctl_driver/hvac_ctl.h>

#include "IfxPort.h"
#include "IfxPort_PinMap.h"


// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

IfxCpu_syncEvent g_cpuSyncEvent = 0;

TestCnt stTestCnt;

Hvac g_hvac;         // HVAC control data
Sensor_Data g_data;   // HVAC sensor data

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);



    sensor_init(&g_data);  // 센서 데이터 초기화
    hvac_init(&g_hvac);    // HVAC 초기화

    initShellInterface();
    Driver_Stm_Init();
    Driver_MQ135_Init();
    Driver_MHZ19B_Init();
    //initASCLIN0Interface(); // mh-z19b ASCLIN(UART) 초기화

    while(1)
    {
        AppScheduling();
    }
}



void AppTask1ms(void)
{

    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;

    print("\n\r");

    // 1. MQ135
    uint32 mq135_adcval = 0;
    mq135_adcval = Driver_Adc0_DataObtain();   // mq135 val평소 1600
    Driver_Adc0_ConvStart();

    print("< MQ135 >\n\r");
    print("adcval      : %d\n\r", mq135_adcval);

    // 2. DHT22
    DHT22_Data dht22_data;
    if(stTestCnt.u32nuCnt1000ms % 2){        // DHT22 Period = 2s
        int result = DHT22_process(&dht22_data);  // DHT22 데이터 읽기
        if(!result){
            print("< DHT22 > \n\r");
            print("temperature : %.1lf\n\r", (double)dht22_data.temperature/10);
            print("humidity    : %.1lf\n\r", (double)dht22_data.humidity/10);
        }
        else{
            print("DHT22 Error : %d\n\r", result);
        }
    }

    // 3. MH-Z19B
    uint16 mhz19b_value = 0;
    uint16 mhz19b_ret = MHZ19B_requestCO2(&mhz19b_value);
    if(mhz19b_ret == -1 || mhz19b_ret == 2){
        print("MH-Z19B Error, %d\n\r", mhz19b_value);
    }
    else{
        print("< MH-Z19B >\n\r");
        print("CO2        : %d ppm\n\r", mhz19b_value);
    }


    // 4. Fan Control
    g_data.ext_air = mq135_adcval;         // 외부 공기질
    g_data.int_co2 = mhz19b_value;        // 내부 CO2 농도
    g_data.int_temperature = (double)dht22_data.temperature/10; // 내부 온도
    g_data.int_humidity = (double)dht22_data.humidity/10;     // 내부 습도
    int hvac_ret = havc_control(&g_hvac, g_data);  // 센서 데이터 바탕으로 팬 제어 함수 호출

    if(!hvac_ret){
        print("HVAC Mode  : %d\n\r", g_hvac.mode);
        print("HVAC Speed : %d\n\r", g_hvac.speed);
    }
    else{
        print("HVAC Error : %dn\r", hvac_ret);
    }

}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}

